# GNU Make project makefile autogenerated by GENie

.SUFFIXES:

ifndef config
  config=debug32
endif

ifndef verbose
  SILENT = @
endif

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(MAKESHELL)))
  SHELLTYPE := posix
endif

ifeq (posix,$(SHELLTYPE))
  MKDIR = $(SILENT) mkdir -p "$(1)"
  COPY  = $(SILENT) cp -fR "$(1)" "$(2)"
  RM    = $(SILENT) rm -f "$(1)"
else
  MKDIR = $(SILENT) mkdir "$(subst /,\\,$(1))" 2> nul || exit 0
  COPY  = $(SILENT) copy /Y "$(subst /,\\,$(1))" "$(subst /,\\,$(2))"
  RM    = $(SILENT) del /F "$(subst /,\\,$(1))" 2> nul || exit 0
endif

CC  = "$(EMSCRIPTEN)/emcc"
CXX = "$(EMSCRIPTEN)/em++"
AR  = "$(EMSCRIPTEN)/emar"

ifndef RESCOMP
  ifdef WINDRES
    RESCOMP = $(WINDRES)
  else
    RESCOMP = windres
  endif
endif

MAKEFILE = Terrasu.make

ifeq ($(config),debug32)
  OBJDIR              = ../../wasm/obj/x32/Debug
  TARGETDIR           = ../../wasm/bin
  TARGET              = $(TARGETDIR)/TerrasuDebug.html
  DEFINES            += -D_DEBUG -DBX_CONFIG_DEBUG=1 -DYAML_CPP_STATIC_DEFINE
  INCLUDES           += -I"../../../3rdParty/bgfx/include" -I"../../../3rdParty/bx/include" -I"../../../3rdParty/bimg/include" -I"../../../3rdParty/SDL/include" -I"../../../3rdParty/glm" -I"../../../3rdParty/entt/src" -I"../../../3rdParty/yaml-cpp/include" -I"../../../3rdParty/imgui" -I"../../../3rdParty/bgfx-imgui/bgfx-imgui" -I"../../../src/include"
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -g -m32 -Wunused-value -Wundef -stdlib=libc++ -g -pthread
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -g -m32 -Wunused-value -Wundef -stdlib=libc++ -g -pthread
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -g -m32 -std=c++17 -Wunused-value -Wundef -stdlib=libc++ -g -pthread
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -g -m32 -Wunused-value -Wundef -stdlib=libc++ -g -pthread
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -g -m32 -std=c++17 -Wunused-value -Wundef -stdlib=libc++ -g -pthread
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -L"../../../3rdparty/lib/wasm" -m32 -s MAX_WEBGL_VERSION=2 ../../../3rdParty/bgfx/.build/wasm/bin/bxDebug.bc ../../../3rdParty/bgfx/.build/wasm/bin/bimgDebug.bc ../../../3rdParty/bgfx/.build/wasm/bin/bimg_decodeDebug.bc ../../../3rdParty/bgfx/.build/wasm/bin/bgfxDebug.bc -s TOTAL_MEMORY=32MB -s ALLOW_MEMORY_GROWTH=1 -s NO_DISABLE_EXCEPTION_CATCHING -s EMULATE_FUNCTION_POINTER_CASTS -s USE_SDL=2 -s NO_EXIT_RUNTIME=0 --preload-file ../../../Assets -g -gsource-map
  LIBDEPS            +=
  LDDEPS             +=
  LDRESP              =
  LIBS               += $(LDDEPS)
  EXTERNAL_LIBS      +=
  LINKOBJS            = $(OBJECTS)
  LINKCMD             = $(CXX) -o $(TARGET) $(LINKOBJS) $(RESOURCES) $(ARCH) $(ALL_LDFLAGS) $(LIBS)
  OBJRESP             =
  OBJECTS := \
	$(OBJDIR)/3rdParty/bgfx-imgui/bgfx-imgui/imgui_impl_bgfx.o \
	$(OBJDIR)/3rdParty/imgui/backends/imgui_impl_sdl2.o \
	$(OBJDIR)/3rdParty/imgui/imgui.o \
	$(OBJDIR)/3rdParty/imgui/imgui_demo.o \
	$(OBJDIR)/3rdParty/imgui/imgui_draw.o \
	$(OBJDIR)/3rdParty/imgui/imgui_tables.o \
	$(OBJDIR)/3rdParty/imgui/imgui_widgets.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/binary.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/contrib/graphbuilder.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/contrib/graphbuilderadapter.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/convert.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/depthguard.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/directives.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/emit.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/emitfromevents.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/emitter.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/emitterstate.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/emitterutils.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/exceptions.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/exp.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/memory.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/node.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/node_data.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/nodebuilder.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/nodeevents.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/null.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/ostream_wrapper.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/parse.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/parser.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/regex_yaml.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/scanner.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/scanscalar.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/scantag.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/scantoken.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/simplekey.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/singledocparser.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/stream.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/tag.o \
	$(OBJDIR)/src/Application.o \
	$(OBJDIR)/src/ComponentPanel.o \
	$(OBJDIR)/src/Core/AssetManager.o \
	$(OBJDIR)/src/Core/Renderer.o \
	$(OBJDIR)/src/ECS/Entity.o \
	$(OBJDIR)/src/ECS/Scene.o \
	$(OBJDIR)/src/SceneSerializer.o \
	$(OBJDIR)/src/Scripts/BulletScript.o \
	$(OBJDIR)/src/Scripts/CameraScript.o \
	$(OBJDIR)/src/Scripts/EndScreenScript.o \
	$(OBJDIR)/src/Scripts/EnemyScript.o \
	$(OBJDIR)/src/Scripts/EnemySpawnerScript.o \
	$(OBJDIR)/src/Scripts/HealthPackScript.o \
	$(OBJDIR)/src/Scripts/NativeScriptComponent.o \
	$(OBJDIR)/src/Scripts/PlayerScript.o \
	$(OBJDIR)/src/Scripts/WeaponPickupScript.o \
	$(OBJDIR)/src/Scripts/WeaponSpawnerScript.o \
	$(OBJDIR)/src/main.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release32)
  OBJDIR              = ../../wasm/obj/x32/Release
  TARGETDIR           = ../../wasm/bin
  TARGET              = $(TARGETDIR)/TerrasuRelease.html
  DEFINES            += -DNDEBUG
  INCLUDES           += -I"../../../3rdParty/bgfx/include" -I"../../../3rdParty/bx/include" -I"../../../3rdParty/bimg/include" -I"../../../3rdParty/SDL/include" -I"../../../3rdParty/glm" -I"../../../3rdParty/entt/src" -I"../../../3rdParty/yaml-cpp/include" -I"../../../3rdParty/imgui" -I"../../../3rdParty/bgfx-imgui/bgfx-imgui" -I"../../../src/include"
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -m32 -Wunused-value -Wundef -stdlib=libc++ -g -pthread
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -m32 -Wunused-value -Wundef -stdlib=libc++ -g -pthread
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -m32 -std=c++17 -Wunused-value -Wundef -stdlib=libc++ -g -pthread
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -m32 -Wunused-value -Wundef -stdlib=libc++ -g -pthread
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -m32 -std=c++17 -Wunused-value -Wundef -stdlib=libc++ -g -pthread
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -L"../../../3rdparty/lib/wasm" -s -m32 -s MAX_WEBGL_VERSION=2 ../../../3rdParty/bgfx/.build/wasm/bin/bxDebug.bc ../../../3rdParty/bgfx/.build/wasm/bin/bimgDebug.bc ../../../3rdParty/bgfx/.build/wasm/bin/bimg_decodeDebug.bc ../../../3rdParty/bgfx/.build/wasm/bin/bgfxDebug.bc -s TOTAL_MEMORY=32MB -s ALLOW_MEMORY_GROWTH=1 -s NO_DISABLE_EXCEPTION_CATCHING -s EMULATE_FUNCTION_POINTER_CASTS -s USE_SDL=2 -s NO_EXIT_RUNTIME=0 --preload-file ../../../Assets -g -gsource-map
  LIBDEPS            +=
  LDDEPS             +=
  LDRESP              =
  LIBS               += $(LDDEPS)
  EXTERNAL_LIBS      +=
  LINKOBJS            = $(OBJECTS)
  LINKCMD             = $(CXX) -o $(TARGET) $(LINKOBJS) $(RESOURCES) $(ARCH) $(ALL_LDFLAGS) $(LIBS)
  OBJRESP             =
  OBJECTS := \
	$(OBJDIR)/3rdParty/bgfx-imgui/bgfx-imgui/imgui_impl_bgfx.o \
	$(OBJDIR)/3rdParty/imgui/backends/imgui_impl_sdl2.o \
	$(OBJDIR)/3rdParty/imgui/imgui.o \
	$(OBJDIR)/3rdParty/imgui/imgui_demo.o \
	$(OBJDIR)/3rdParty/imgui/imgui_draw.o \
	$(OBJDIR)/3rdParty/imgui/imgui_tables.o \
	$(OBJDIR)/3rdParty/imgui/imgui_widgets.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/binary.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/contrib/graphbuilder.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/contrib/graphbuilderadapter.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/convert.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/depthguard.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/directives.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/emit.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/emitfromevents.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/emitter.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/emitterstate.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/emitterutils.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/exceptions.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/exp.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/memory.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/node.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/node_data.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/nodebuilder.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/nodeevents.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/null.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/ostream_wrapper.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/parse.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/parser.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/regex_yaml.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/scanner.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/scanscalar.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/scantag.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/scantoken.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/simplekey.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/singledocparser.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/stream.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/tag.o \
	$(OBJDIR)/src/Application.o \
	$(OBJDIR)/src/ComponentPanel.o \
	$(OBJDIR)/src/Core/AssetManager.o \
	$(OBJDIR)/src/Core/Renderer.o \
	$(OBJDIR)/src/ECS/Entity.o \
	$(OBJDIR)/src/ECS/Scene.o \
	$(OBJDIR)/src/SceneSerializer.o \
	$(OBJDIR)/src/Scripts/BulletScript.o \
	$(OBJDIR)/src/Scripts/CameraScript.o \
	$(OBJDIR)/src/Scripts/EndScreenScript.o \
	$(OBJDIR)/src/Scripts/EnemyScript.o \
	$(OBJDIR)/src/Scripts/EnemySpawnerScript.o \
	$(OBJDIR)/src/Scripts/HealthPackScript.o \
	$(OBJDIR)/src/Scripts/NativeScriptComponent.o \
	$(OBJDIR)/src/Scripts/PlayerScript.o \
	$(OBJDIR)/src/Scripts/WeaponPickupScript.o \
	$(OBJDIR)/src/Scripts/WeaponSpawnerScript.o \
	$(OBJDIR)/src/main.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug64)
  OBJDIR              = ../../wasm/obj/x64/Debug
  TARGETDIR           = ../../wasm/bin
  TARGET              = $(TARGETDIR)/TerrasuDebug.html
  DEFINES            += -D_DEBUG -DBX_CONFIG_DEBUG=1 -DYAML_CPP_STATIC_DEFINE
  INCLUDES           += -I"../../../3rdParty/bgfx/include" -I"../../../3rdParty/bx/include" -I"../../../3rdParty/bimg/include" -I"../../../3rdParty/SDL/include" -I"../../../3rdParty/glm" -I"../../../3rdParty/entt/src" -I"../../../3rdParty/yaml-cpp/include" -I"../../../3rdParty/imgui" -I"../../../3rdParty/bgfx-imgui/bgfx-imgui" -I"../../../src/include"
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -g -m64 -Wunused-value -Wundef -stdlib=libc++ -g -pthread
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -g -m64 -Wunused-value -Wundef -stdlib=libc++ -g -pthread
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -g -m64 -std=c++17 -Wunused-value -Wundef -stdlib=libc++ -g -pthread
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -g -m64 -Wunused-value -Wundef -stdlib=libc++ -g -pthread
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -g -m64 -std=c++17 -Wunused-value -Wundef -stdlib=libc++ -g -pthread
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -L"../../../3rdparty/lib/wasm" -m64 -s MAX_WEBGL_VERSION=2 ../../../3rdParty/bgfx/.build/wasm/bin/bxDebug.bc ../../../3rdParty/bgfx/.build/wasm/bin/bimgDebug.bc ../../../3rdParty/bgfx/.build/wasm/bin/bimg_decodeDebug.bc ../../../3rdParty/bgfx/.build/wasm/bin/bgfxDebug.bc -s TOTAL_MEMORY=32MB -s ALLOW_MEMORY_GROWTH=1 -s NO_DISABLE_EXCEPTION_CATCHING -s EMULATE_FUNCTION_POINTER_CASTS -s USE_SDL=2 -s NO_EXIT_RUNTIME=0 --preload-file ../../../Assets -g -gsource-map
  LIBDEPS            +=
  LDDEPS             +=
  LDRESP              =
  LIBS               += $(LDDEPS)
  EXTERNAL_LIBS      +=
  LINKOBJS            = $(OBJECTS)
  LINKCMD             = $(CXX) -o $(TARGET) $(LINKOBJS) $(RESOURCES) $(ARCH) $(ALL_LDFLAGS) $(LIBS)
  OBJRESP             =
  OBJECTS := \
	$(OBJDIR)/3rdParty/bgfx-imgui/bgfx-imgui/imgui_impl_bgfx.o \
	$(OBJDIR)/3rdParty/imgui/backends/imgui_impl_sdl2.o \
	$(OBJDIR)/3rdParty/imgui/imgui.o \
	$(OBJDIR)/3rdParty/imgui/imgui_demo.o \
	$(OBJDIR)/3rdParty/imgui/imgui_draw.o \
	$(OBJDIR)/3rdParty/imgui/imgui_tables.o \
	$(OBJDIR)/3rdParty/imgui/imgui_widgets.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/binary.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/contrib/graphbuilder.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/contrib/graphbuilderadapter.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/convert.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/depthguard.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/directives.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/emit.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/emitfromevents.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/emitter.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/emitterstate.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/emitterutils.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/exceptions.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/exp.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/memory.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/node.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/node_data.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/nodebuilder.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/nodeevents.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/null.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/ostream_wrapper.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/parse.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/parser.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/regex_yaml.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/scanner.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/scanscalar.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/scantag.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/scantoken.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/simplekey.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/singledocparser.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/stream.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/tag.o \
	$(OBJDIR)/src/Application.o \
	$(OBJDIR)/src/ComponentPanel.o \
	$(OBJDIR)/src/Core/AssetManager.o \
	$(OBJDIR)/src/Core/Renderer.o \
	$(OBJDIR)/src/ECS/Entity.o \
	$(OBJDIR)/src/ECS/Scene.o \
	$(OBJDIR)/src/SceneSerializer.o \
	$(OBJDIR)/src/Scripts/BulletScript.o \
	$(OBJDIR)/src/Scripts/CameraScript.o \
	$(OBJDIR)/src/Scripts/EndScreenScript.o \
	$(OBJDIR)/src/Scripts/EnemyScript.o \
	$(OBJDIR)/src/Scripts/EnemySpawnerScript.o \
	$(OBJDIR)/src/Scripts/HealthPackScript.o \
	$(OBJDIR)/src/Scripts/NativeScriptComponent.o \
	$(OBJDIR)/src/Scripts/PlayerScript.o \
	$(OBJDIR)/src/Scripts/WeaponPickupScript.o \
	$(OBJDIR)/src/Scripts/WeaponSpawnerScript.o \
	$(OBJDIR)/src/main.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release64)
  OBJDIR              = ../../wasm/obj/x64/Release
  TARGETDIR           = ../../wasm/bin
  TARGET              = $(TARGETDIR)/TerrasuRelease.html
  DEFINES            += -DNDEBUG
  INCLUDES           += -I"../../../3rdParty/bgfx/include" -I"../../../3rdParty/bx/include" -I"../../../3rdParty/bimg/include" -I"../../../3rdParty/SDL/include" -I"../../../3rdParty/glm" -I"../../../3rdParty/entt/src" -I"../../../3rdParty/yaml-cpp/include" -I"../../../3rdParty/imgui" -I"../../../3rdParty/bgfx-imgui/bgfx-imgui" -I"../../../src/include"
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -m64 -Wunused-value -Wundef -stdlib=libc++ -g -pthread
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -m64 -Wunused-value -Wundef -stdlib=libc++ -g -pthread
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -m64 -std=c++17 -Wunused-value -Wundef -stdlib=libc++ -g -pthread
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -m64 -Wunused-value -Wundef -stdlib=libc++ -g -pthread
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -m64 -std=c++17 -Wunused-value -Wundef -stdlib=libc++ -g -pthread
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -L"../../../3rdparty/lib/wasm" -s -m64 -s MAX_WEBGL_VERSION=2 ../../../3rdParty/bgfx/.build/wasm/bin/bxDebug.bc ../../../3rdParty/bgfx/.build/wasm/bin/bimgDebug.bc ../../../3rdParty/bgfx/.build/wasm/bin/bimg_decodeDebug.bc ../../../3rdParty/bgfx/.build/wasm/bin/bgfxDebug.bc -s TOTAL_MEMORY=32MB -s ALLOW_MEMORY_GROWTH=1 -s NO_DISABLE_EXCEPTION_CATCHING -s EMULATE_FUNCTION_POINTER_CASTS -s USE_SDL=2 -s NO_EXIT_RUNTIME=0 --preload-file ../../../Assets -g -gsource-map
  LIBDEPS            +=
  LDDEPS             +=
  LDRESP              =
  LIBS               += $(LDDEPS)
  EXTERNAL_LIBS      +=
  LINKOBJS            = $(OBJECTS)
  LINKCMD             = $(CXX) -o $(TARGET) $(LINKOBJS) $(RESOURCES) $(ARCH) $(ALL_LDFLAGS) $(LIBS)
  OBJRESP             =
  OBJECTS := \
	$(OBJDIR)/3rdParty/bgfx-imgui/bgfx-imgui/imgui_impl_bgfx.o \
	$(OBJDIR)/3rdParty/imgui/backends/imgui_impl_sdl2.o \
	$(OBJDIR)/3rdParty/imgui/imgui.o \
	$(OBJDIR)/3rdParty/imgui/imgui_demo.o \
	$(OBJDIR)/3rdParty/imgui/imgui_draw.o \
	$(OBJDIR)/3rdParty/imgui/imgui_tables.o \
	$(OBJDIR)/3rdParty/imgui/imgui_widgets.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/binary.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/contrib/graphbuilder.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/contrib/graphbuilderadapter.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/convert.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/depthguard.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/directives.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/emit.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/emitfromevents.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/emitter.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/emitterstate.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/emitterutils.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/exceptions.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/exp.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/memory.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/node.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/node_data.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/nodebuilder.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/nodeevents.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/null.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/ostream_wrapper.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/parse.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/parser.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/regex_yaml.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/scanner.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/scanscalar.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/scantag.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/scantoken.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/simplekey.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/singledocparser.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/stream.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/tag.o \
	$(OBJDIR)/src/Application.o \
	$(OBJDIR)/src/ComponentPanel.o \
	$(OBJDIR)/src/Core/AssetManager.o \
	$(OBJDIR)/src/Core/Renderer.o \
	$(OBJDIR)/src/ECS/Entity.o \
	$(OBJDIR)/src/ECS/Scene.o \
	$(OBJDIR)/src/SceneSerializer.o \
	$(OBJDIR)/src/Scripts/BulletScript.o \
	$(OBJDIR)/src/Scripts/CameraScript.o \
	$(OBJDIR)/src/Scripts/EndScreenScript.o \
	$(OBJDIR)/src/Scripts/EnemyScript.o \
	$(OBJDIR)/src/Scripts/EnemySpawnerScript.o \
	$(OBJDIR)/src/Scripts/HealthPackScript.o \
	$(OBJDIR)/src/Scripts/NativeScriptComponent.o \
	$(OBJDIR)/src/Scripts/PlayerScript.o \
	$(OBJDIR)/src/Scripts/WeaponPickupScript.o \
	$(OBJDIR)/src/Scripts/WeaponSpawnerScript.o \
	$(OBJDIR)/src/main.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug)
  OBJDIR              = ../../wasm/obj/Debug
  TARGETDIR           = ../../wasm/bin
  TARGET              = $(TARGETDIR)/TerrasuDebug.html
  DEFINES            += -D_DEBUG -DBX_CONFIG_DEBUG=1 -DYAML_CPP_STATIC_DEFINE
  INCLUDES           += -I"../../../3rdParty/bgfx/include" -I"../../../3rdParty/bx/include" -I"../../../3rdParty/bimg/include" -I"../../../3rdParty/SDL/include" -I"../../../3rdParty/glm" -I"../../../3rdParty/entt/src" -I"../../../3rdParty/yaml-cpp/include" -I"../../../3rdParty/imgui" -I"../../../3rdParty/bgfx-imgui/bgfx-imgui" -I"../../../src/include"
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -g -Wunused-value -Wundef -stdlib=libc++ -g -pthread
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -g -Wunused-value -Wundef -stdlib=libc++ -g -pthread
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -g -std=c++17 -Wunused-value -Wundef -stdlib=libc++ -g -pthread
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -g -Wunused-value -Wundef -stdlib=libc++ -g -pthread
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -g -std=c++17 -Wunused-value -Wundef -stdlib=libc++ -g -pthread
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -L"../../../3rdparty/lib/wasm" -s MAX_WEBGL_VERSION=2 ../../../3rdParty/bgfx/.build/wasm/bin/bxDebug.bc ../../../3rdParty/bgfx/.build/wasm/bin/bimgDebug.bc ../../../3rdParty/bgfx/.build/wasm/bin/bimg_decodeDebug.bc ../../../3rdParty/bgfx/.build/wasm/bin/bgfxDebug.bc -s TOTAL_MEMORY=32MB -s ALLOW_MEMORY_GROWTH=1 -s NO_DISABLE_EXCEPTION_CATCHING -s EMULATE_FUNCTION_POINTER_CASTS -s USE_SDL=2 -s NO_EXIT_RUNTIME=0 --preload-file ../../../Assets -g -gsource-map
  LIBDEPS            +=
  LDDEPS             +=
  LDRESP              =
  LIBS               += $(LDDEPS)
  EXTERNAL_LIBS      +=
  LINKOBJS            = $(OBJECTS)
  LINKCMD             = $(CXX) -o $(TARGET) $(LINKOBJS) $(RESOURCES) $(ARCH) $(ALL_LDFLAGS) $(LIBS)
  OBJRESP             =
  OBJECTS := \
	$(OBJDIR)/3rdParty/bgfx-imgui/bgfx-imgui/imgui_impl_bgfx.o \
	$(OBJDIR)/3rdParty/imgui/backends/imgui_impl_sdl2.o \
	$(OBJDIR)/3rdParty/imgui/imgui.o \
	$(OBJDIR)/3rdParty/imgui/imgui_demo.o \
	$(OBJDIR)/3rdParty/imgui/imgui_draw.o \
	$(OBJDIR)/3rdParty/imgui/imgui_tables.o \
	$(OBJDIR)/3rdParty/imgui/imgui_widgets.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/binary.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/contrib/graphbuilder.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/contrib/graphbuilderadapter.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/convert.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/depthguard.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/directives.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/emit.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/emitfromevents.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/emitter.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/emitterstate.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/emitterutils.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/exceptions.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/exp.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/memory.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/node.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/node_data.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/nodebuilder.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/nodeevents.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/null.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/ostream_wrapper.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/parse.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/parser.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/regex_yaml.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/scanner.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/scanscalar.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/scantag.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/scantoken.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/simplekey.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/singledocparser.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/stream.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/tag.o \
	$(OBJDIR)/src/Application.o \
	$(OBJDIR)/src/ComponentPanel.o \
	$(OBJDIR)/src/Core/AssetManager.o \
	$(OBJDIR)/src/Core/Renderer.o \
	$(OBJDIR)/src/ECS/Entity.o \
	$(OBJDIR)/src/ECS/Scene.o \
	$(OBJDIR)/src/SceneSerializer.o \
	$(OBJDIR)/src/Scripts/BulletScript.o \
	$(OBJDIR)/src/Scripts/CameraScript.o \
	$(OBJDIR)/src/Scripts/EndScreenScript.o \
	$(OBJDIR)/src/Scripts/EnemyScript.o \
	$(OBJDIR)/src/Scripts/EnemySpawnerScript.o \
	$(OBJDIR)/src/Scripts/HealthPackScript.o \
	$(OBJDIR)/src/Scripts/NativeScriptComponent.o \
	$(OBJDIR)/src/Scripts/PlayerScript.o \
	$(OBJDIR)/src/Scripts/WeaponPickupScript.o \
	$(OBJDIR)/src/Scripts/WeaponSpawnerScript.o \
	$(OBJDIR)/src/main.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release)
  OBJDIR              = ../../wasm/obj/Release
  TARGETDIR           = ../../wasm/bin
  TARGET              = $(TARGETDIR)/TerrasuRelease.html
  DEFINES            += -DNDEBUG
  INCLUDES           += -I"../../../3rdParty/bgfx/include" -I"../../../3rdParty/bx/include" -I"../../../3rdParty/bimg/include" -I"../../../3rdParty/SDL/include" -I"../../../3rdParty/glm" -I"../../../3rdParty/entt/src" -I"../../../3rdParty/yaml-cpp/include" -I"../../../3rdParty/imgui" -I"../../../3rdParty/bgfx-imgui/bgfx-imgui" -I"../../../src/include"
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -Wunused-value -Wundef -stdlib=libc++ -g -pthread
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -Wunused-value -Wundef -stdlib=libc++ -g -pthread
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -std=c++17 -Wunused-value -Wundef -stdlib=libc++ -g -pthread
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -Wunused-value -Wundef -stdlib=libc++ -g -pthread
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -std=c++17 -Wunused-value -Wundef -stdlib=libc++ -g -pthread
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -L"../../../3rdparty/lib/wasm" -s -s MAX_WEBGL_VERSION=2 ../../../3rdParty/bgfx/.build/wasm/bin/bxDebug.bc ../../../3rdParty/bgfx/.build/wasm/bin/bimgDebug.bc ../../../3rdParty/bgfx/.build/wasm/bin/bimg_decodeDebug.bc ../../../3rdParty/bgfx/.build/wasm/bin/bgfxDebug.bc -s TOTAL_MEMORY=32MB -s ALLOW_MEMORY_GROWTH=1 -s NO_DISABLE_EXCEPTION_CATCHING -s EMULATE_FUNCTION_POINTER_CASTS -s USE_SDL=2 -s NO_EXIT_RUNTIME=0 --preload-file ../../../Assets -g -gsource-map
  LIBDEPS            +=
  LDDEPS             +=
  LDRESP              =
  LIBS               += $(LDDEPS)
  EXTERNAL_LIBS      +=
  LINKOBJS            = $(OBJECTS)
  LINKCMD             = $(CXX) -o $(TARGET) $(LINKOBJS) $(RESOURCES) $(ARCH) $(ALL_LDFLAGS) $(LIBS)
  OBJRESP             =
  OBJECTS := \
	$(OBJDIR)/3rdParty/bgfx-imgui/bgfx-imgui/imgui_impl_bgfx.o \
	$(OBJDIR)/3rdParty/imgui/backends/imgui_impl_sdl2.o \
	$(OBJDIR)/3rdParty/imgui/imgui.o \
	$(OBJDIR)/3rdParty/imgui/imgui_demo.o \
	$(OBJDIR)/3rdParty/imgui/imgui_draw.o \
	$(OBJDIR)/3rdParty/imgui/imgui_tables.o \
	$(OBJDIR)/3rdParty/imgui/imgui_widgets.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/binary.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/contrib/graphbuilder.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/contrib/graphbuilderadapter.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/convert.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/depthguard.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/directives.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/emit.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/emitfromevents.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/emitter.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/emitterstate.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/emitterutils.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/exceptions.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/exp.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/memory.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/node.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/node_data.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/nodebuilder.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/nodeevents.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/null.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/ostream_wrapper.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/parse.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/parser.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/regex_yaml.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/scanner.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/scanscalar.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/scantag.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/scantoken.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/simplekey.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/singledocparser.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/stream.o \
	$(OBJDIR)/3rdParty/yaml-cpp/src/tag.o \
	$(OBJDIR)/src/Application.o \
	$(OBJDIR)/src/ComponentPanel.o \
	$(OBJDIR)/src/Core/AssetManager.o \
	$(OBJDIR)/src/Core/Renderer.o \
	$(OBJDIR)/src/ECS/Entity.o \
	$(OBJDIR)/src/ECS/Scene.o \
	$(OBJDIR)/src/SceneSerializer.o \
	$(OBJDIR)/src/Scripts/BulletScript.o \
	$(OBJDIR)/src/Scripts/CameraScript.o \
	$(OBJDIR)/src/Scripts/EndScreenScript.o \
	$(OBJDIR)/src/Scripts/EnemyScript.o \
	$(OBJDIR)/src/Scripts/EnemySpawnerScript.o \
	$(OBJDIR)/src/Scripts/HealthPackScript.o \
	$(OBJDIR)/src/Scripts/NativeScriptComponent.o \
	$(OBJDIR)/src/Scripts/PlayerScript.o \
	$(OBJDIR)/src/Scripts/WeaponPickupScript.o \
	$(OBJDIR)/src/Scripts/WeaponSpawnerScript.o \
	$(OBJDIR)/src/main.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJDIRS := \
	$(OBJDIR) \
	$(OBJDIR)/3rdParty/bgfx-imgui/bgfx-imgui \
	$(OBJDIR)/3rdParty/imgui \
	$(OBJDIR)/3rdParty/imgui/backends \
	$(OBJDIR)/3rdParty/yaml-cpp/src \
	$(OBJDIR)/3rdParty/yaml-cpp/src/contrib \
	$(OBJDIR)/src \
	$(OBJDIR)/src/Core \
	$(OBJDIR)/src/ECS \
	$(OBJDIR)/src/Scripts \

RESOURCES := \

.PHONY: clean prebuild prelink

all: $(OBJDIRS) $(TARGETDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LIBDEPS) $(EXTERNAL_LIBS) $(RESOURCES) $(OBJRESP) $(LDRESP) | $(TARGETDIR) $(OBJDIRS)
	@echo Linking Terrasu
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
	-$(call MKDIR,$(TARGETDIR))

$(OBJDIRS):
	@echo Creating $(@)
	-$(call MKDIR,$@)

clean:
	@echo Cleaning Terrasu
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH) $(MAKEFILE) | $(OBJDIR)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) -x c++-header $(DEFINES) $(INCLUDES) -o "$@" -c "$<"

$(GCH_OBJC): $(PCH) $(MAKEFILE) | $(OBJDIR)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_OBJCPPFLAGS) -x objective-c++-header $(DEFINES) $(INCLUDES) -o "$@" -c "$<"
endif

ifneq (,$(OBJRESP))
$(OBJRESP): $(OBJECTS) | $(TARGETDIR) $(OBJDIRS)
	$(SILENT) echo $^
	$(SILENT) echo $^ > $@
endif

ifneq (,$(LDRESP))
$(LDRESP): $(LDDEPS) | $(TARGETDIR) $(OBJDIRS)
	$(SILENT) echo $^
	$(SILENT) echo $^ > $@
endif

$(OBJDIR)/3rdParty/bgfx-imgui/bgfx-imgui/imgui_impl_bgfx.o: ../../../3rdParty/bgfx-imgui/bgfx-imgui/imgui_impl_bgfx.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/bgfx-imgui/bgfx-imgui
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/imgui/backends/imgui_impl_sdl2.o: ../../../3rdParty/imgui/backends/imgui_impl_sdl2.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/imgui/backends
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/imgui/imgui.o: ../../../3rdParty/imgui/imgui.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/imgui
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/imgui/imgui_demo.o: ../../../3rdParty/imgui/imgui_demo.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/imgui
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/imgui/imgui_draw.o: ../../../3rdParty/imgui/imgui_draw.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/imgui
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/imgui/imgui_tables.o: ../../../3rdParty/imgui/imgui_tables.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/imgui
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/imgui/imgui_widgets.o: ../../../3rdParty/imgui/imgui_widgets.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/imgui
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/yaml-cpp/src/binary.o: ../../../3rdParty/yaml-cpp/src/binary.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/yaml-cpp/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/yaml-cpp/src/contrib/graphbuilder.o: ../../../3rdParty/yaml-cpp/src/contrib/graphbuilder.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/yaml-cpp/src/contrib
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/yaml-cpp/src/contrib/graphbuilderadapter.o: ../../../3rdParty/yaml-cpp/src/contrib/graphbuilderadapter.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/yaml-cpp/src/contrib
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/yaml-cpp/src/convert.o: ../../../3rdParty/yaml-cpp/src/convert.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/yaml-cpp/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/yaml-cpp/src/depthguard.o: ../../../3rdParty/yaml-cpp/src/depthguard.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/yaml-cpp/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/yaml-cpp/src/directives.o: ../../../3rdParty/yaml-cpp/src/directives.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/yaml-cpp/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/yaml-cpp/src/emit.o: ../../../3rdParty/yaml-cpp/src/emit.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/yaml-cpp/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/yaml-cpp/src/emitfromevents.o: ../../../3rdParty/yaml-cpp/src/emitfromevents.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/yaml-cpp/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/yaml-cpp/src/emitter.o: ../../../3rdParty/yaml-cpp/src/emitter.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/yaml-cpp/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/yaml-cpp/src/emitterstate.o: ../../../3rdParty/yaml-cpp/src/emitterstate.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/yaml-cpp/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/yaml-cpp/src/emitterutils.o: ../../../3rdParty/yaml-cpp/src/emitterutils.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/yaml-cpp/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/yaml-cpp/src/exceptions.o: ../../../3rdParty/yaml-cpp/src/exceptions.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/yaml-cpp/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/yaml-cpp/src/exp.o: ../../../3rdParty/yaml-cpp/src/exp.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/yaml-cpp/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/yaml-cpp/src/memory.o: ../../../3rdParty/yaml-cpp/src/memory.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/yaml-cpp/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/yaml-cpp/src/node.o: ../../../3rdParty/yaml-cpp/src/node.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/yaml-cpp/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/yaml-cpp/src/node_data.o: ../../../3rdParty/yaml-cpp/src/node_data.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/yaml-cpp/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/yaml-cpp/src/nodebuilder.o: ../../../3rdParty/yaml-cpp/src/nodebuilder.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/yaml-cpp/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/yaml-cpp/src/nodeevents.o: ../../../3rdParty/yaml-cpp/src/nodeevents.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/yaml-cpp/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/yaml-cpp/src/null.o: ../../../3rdParty/yaml-cpp/src/null.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/yaml-cpp/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/yaml-cpp/src/ostream_wrapper.o: ../../../3rdParty/yaml-cpp/src/ostream_wrapper.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/yaml-cpp/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/yaml-cpp/src/parse.o: ../../../3rdParty/yaml-cpp/src/parse.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/yaml-cpp/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/yaml-cpp/src/parser.o: ../../../3rdParty/yaml-cpp/src/parser.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/yaml-cpp/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/yaml-cpp/src/regex_yaml.o: ../../../3rdParty/yaml-cpp/src/regex_yaml.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/yaml-cpp/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/yaml-cpp/src/scanner.o: ../../../3rdParty/yaml-cpp/src/scanner.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/yaml-cpp/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/yaml-cpp/src/scanscalar.o: ../../../3rdParty/yaml-cpp/src/scanscalar.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/yaml-cpp/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/yaml-cpp/src/scantag.o: ../../../3rdParty/yaml-cpp/src/scantag.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/yaml-cpp/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/yaml-cpp/src/scantoken.o: ../../../3rdParty/yaml-cpp/src/scantoken.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/yaml-cpp/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/yaml-cpp/src/simplekey.o: ../../../3rdParty/yaml-cpp/src/simplekey.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/yaml-cpp/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/yaml-cpp/src/singledocparser.o: ../../../3rdParty/yaml-cpp/src/singledocparser.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/yaml-cpp/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/yaml-cpp/src/stream.o: ../../../3rdParty/yaml-cpp/src/stream.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/yaml-cpp/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/3rdParty/yaml-cpp/src/tag.o: ../../../3rdParty/yaml-cpp/src/tag.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/3rdParty/yaml-cpp/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/Application.o: ../../../src/Application.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/ComponentPanel.o: ../../../src/ComponentPanel.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/Core/AssetManager.o: ../../../src/Core/AssetManager.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/Core
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/Core/Renderer.o: ../../../src/Core/Renderer.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/Core
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/ECS/Entity.o: ../../../src/ECS/Entity.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/ECS
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/ECS/Scene.o: ../../../src/ECS/Scene.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/ECS
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/SceneSerializer.o: ../../../src/SceneSerializer.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/Scripts/BulletScript.o: ../../../src/Scripts/BulletScript.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/Scripts
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/Scripts/CameraScript.o: ../../../src/Scripts/CameraScript.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/Scripts
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/Scripts/EndScreenScript.o: ../../../src/Scripts/EndScreenScript.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/Scripts
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/Scripts/EnemyScript.o: ../../../src/Scripts/EnemyScript.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/Scripts
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/Scripts/EnemySpawnerScript.o: ../../../src/Scripts/EnemySpawnerScript.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/Scripts
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/Scripts/HealthPackScript.o: ../../../src/Scripts/HealthPackScript.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/Scripts
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/Scripts/NativeScriptComponent.o: ../../../src/Scripts/NativeScriptComponent.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/Scripts
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/Scripts/PlayerScript.o: ../../../src/Scripts/PlayerScript.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/Scripts
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/Scripts/WeaponPickupScript.o: ../../../src/Scripts/WeaponPickupScript.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/Scripts
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/Scripts/WeaponSpawnerScript.o: ../../../src/Scripts/WeaponSpawnerScript.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src/Scripts
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/src/main.o: ../../../src/main.cpp $(GCH) $(MAKEFILE) | $(OBJDIR)/src
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(OBJDIR)/$(notdir $(PCH)).d
  -include $(OBJDIR)/$(notdir $(PCH))_objc.d
endif
